odom_topic: "robot/dlo/odom_node/odom"
odom_frame: "odom"
robot_frame: "base_link"
trajectory_topic: "trajectory"
map_frame_id: "TagMap"
pathtosavelandmarkcsv: "config/landmark.csv"
pathtoloadlandmarkcsv: "config/afteroptimisation.csv"
savetaglocation: false
usepriortagtable: true
batch_optimisation: true
total_tags: 1000
add2graph_threshold: 0.2
maxfactors: 50 # maximum number of poses in the factor graph
useprunebysize: true # no point of using it with ISAM2
useisam2: false # true for ISAM2, false for SAM

# Particle initilisation condition 
N_particles: 1000
usePFinitialise: true
PFWaitTime: 5
rngVar: 0.2
brngVar: 0.1

# Loop closure, dont apply LC when pruning is enabled
useloopclosure: false
historyKeyframeSearchRadius: 3 # minimum historyKeyframeSearchRadius meters to be considered loopclosured
historyKeyframeSearchNum: 40 # loopclosure only checking historyKeyframeSearchNum frames apart poses
requiredReobservedLandmarks: 3 

# Stationary threshold
stationary_position_threshold: 0.05 # 5cm
stationary_rotation_threshold: 0.1 # 0.1radius

# Keyframe info, no need to use it if in isam2 mode
usekeyframe: false
distanceThreshold: 0.5
rotationThreshold: 5

# Outlier removal, dont use it when odometry is really bad!!!!!!
useoutlierremoval: true
jumpCombinedThreshold: 1
outlierRemovalStartIndex_: 20 

# Trajectory smooth
usetrajsmoothing: true
smoothingStartIndex_: 20 
smoothingwindow: 5

noise_models:
  odometry:
    - 3
    - 30
    - 3
  prior:
    - 0.1
    - 0.3
    - 0.1
  bearing_range:
    - 0.1
    - 0.8
  point:
    - 0.001
    - 0.001
  loopClosureNoise:
    - 0.5
    - 5
    - 0.5

# Outlier removal
useoutlierremoval: true
# jumpCombinedThreshold: 1.0
outlierRemovalStartIndex_: 20 # give it 20s to initilise before outlier removal kicks in

# Trajectory smooth
usetrajsmoothing: true
smoothingStartIndex_: 20 # give it 20s to initilise before smoother kicks in
smoothingwindow: 5

# Camera configuration
# camera_config:
#   cameras:
#     - name: lCam
#       topic: "/l/tag_detections"
#       frame: "usb_cam_l"
#     - name: rCam
#       topic: "/r/tag_detections"
#       frame: "usb_cam_r"
#     - name: mCam
#       topic: "/m/tag_detections"
#       frame: "usb_cam_m"

use_tf_lookup: false

camera_config:
  cameras:
    - name: picam1
      topic: "/antobot/picam1/tag_detections"
      frame: "picam1"
      transform: [0, 0, 0.39]
    - name: picam2
      topic: "/antobot/picam2/tag_detections"
      frame: "picam2"
      transform: [0, 0, -0.39]
